#pragma once
#include <iostream>
#include <map>
#include <set>
#include <list> 
#include <cmath>
#include <deque>
#include <queue>
#include <stack>
#include <limits>
#include <string>
#include <vector>
#include <numeric>
#include <algorithm>
#include <unordered_map>
#include <sstream>
#include <utility>
#include <numeric>
#include <chrono>
#include <ctime>
#include <memory> 
#include  <variant>
#include <optional>
#include <tuple>
#include <format>
#include <map>
#include <unordered_map>
#include <thread>
#include <condition_variable>
#include <mutex>

